#!/usr/bin/env python3
"""
Jules Batch Submitter for WriterAgent.
Automates the submission of tasks generated by mail_merge_external.py to Google Jules.
"""

import json
import subprocess
import argparse
import logging
import time
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
log = logging.getLogger("jules_submitter")

TASK_DIR = Path("mail_merge_tasks")
TASK_INDEX = TASK_DIR / "task_index.json"
STATUS_FILE = TASK_DIR / "jules_status.json"

def load_status():
    if STATUS_FILE.exists():
        try:
            with open(STATUS_FILE, "r") as f:
                return json.load(f)
        except Exception as e:
            log.error(f"Failed to load status file: {e}")
            return {}
    return {}

def save_status(status):
    try:
        with open(STATUS_FILE, "w") as f:
            json.dump(status, f, indent=2)
    except Exception as e:
        log.error(f"Failed to save status file: {e}")

def run_jules_task(task_id, document_path, dry_run=False):
    """Submits a single task to Jules."""
    if not document_path.exists():
        log.warning(f"Skipping task {task_id}: Document not found at {document_path}")
        return False

    with open(document_path, "r") as f:
        instructions = f.read()

    # The command we want to run:
    # jules remote new --repo . --session "INSTRUCTIONS"
    # We use subprocess.run with the string to handle potential shell escaping issues.
    
    # Explicitly use the repo name as 'jules' seems to fail with '.' in some environments.
    cmd = ["jules", "remote", "new", "--repo", "KeithCu/writeragent", "--session", instructions]
    
    if dry_run:
        print(f"\n[DRY RUN] Task {task_id}: {document_path.name}")
        print(f"Command: {' '.join(cmd[:6])} \"[INSTRUCTIONS]\"")
        return True

    print(f"\n>>> Submitting task {task_id} to Jules...")
    print(f"Executing: {' '.join(cmd[:6])} \"{document_path.name} contents\"")
    
    try:
        # Run the command and capture output
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        # NOTE: Some versions of Jules CLI return 0 even on errors like "repo not found".
        # We check both the return code and the output content.
        is_error = result.returncode != 0 or "Error:" in result.stdout or "Error:" in result.stderr
        
        if not is_error:
            print(f"✅ Successfully submitted task {task_id}")
            if result.stdout:
                print(f"--- Jules Output ---\n{result.stdout.strip()}\n-------------------")
            return True
        else:
            print(f"❌ Failed to submit task {task_id}")
            if result.returncode != 0:
                print(f"Exit code: {result.returncode}")
            if result.stdout:
                print(f"STDOUT:\n{result.stdout.strip()}")
            if result.stderr:
                print(f"STDERR:\n{result.stderr.strip()}")
            return False
            
    except Exception as e:
        print(f"💥 Unexpected error submitting task {task_id}: {str(e)}")
        return False

def main():
    parser = argparse.ArgumentParser(description="Submit WriterAgent tasks to Google Jules in batches.")
    parser.add_argument("--limit", type=int, default=10, help="Maximum number of tasks to submit in this run.")
    parser.add_argument("--dry-run", action="store_true", help="Print the tasks that would be submitted without actually calling Jules.")
    parser.add_argument("--force", action="store_true", help="Re-submit tasks even if they are marked as completed.")
    args = parser.parse_args()

    if not TASK_INDEX.exists():
        log.error(f"Task index not found at {TASK_INDEX}. Have you run the mail_merge script?")
        return

    with open(TASK_INDEX, "r") as f:
        tasks = json.load(f)

    status = load_status()
    submitted_count = 0

    for task in tasks:
        if submitted_count >= args.limit:
            break

        task_id = str(task.get("task_id", "unknown"))
        doc_name = task.get("document")
        
        if not doc_name:
            log.warning(f"Skipping task {task_id}: No 'document' field found in index.")
            continue
            
        doc_path = TASK_DIR / doc_name

        if task_id in status and not args.force:
            continue

        if run_jules_task(task_id, doc_path, dry_run=args.dry_run):
            if not args.dry_run:
                status[task_id] = {
                    "document": doc_name,
                    "submitted_at": subprocess.check_output(["date"]).decode().strip(),
                    "status": "submitted"
                }
                save_status(status)
                
                # Sleep between requests to be friendly to the API
                if submitted_count < args.limit - 1:
                    log.info("Waiting 5 seconds before next submission...")
                    time.sleep(5)
            
            submitted_count += 1

    if submitted_count == 0:
        print("\n✨ No new tasks to submit.")
    else:
        print(f"\n🚀 Batch completed. Successfully submitted {submitted_count} tasks.")

if __name__ == "__main__":
    main()
