#!/usr/bin/env python3
"""
ABOUTME: LibreOffice and WriterAgent document export and scientific compute bridge for OpenDraft.
ABOUTME: Converts Markdown research drafts into native .odt, .docx, .pdf, and LaTeX with math preservation.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, cast


def find_libreoffice() -> Optional[Path]:
    """Locate the LibreOffice (soffice) executable on the current system."""
    # Check system PATH
    soffice_path = shutil.which("soffice")
    if soffice_path:
        return Path(soffice_path)

    # Common Windows locations
    windows_candidates = [
        Path(r"C:\Program Files\LibreOffice\program\soffice.exe"),
        Path(r"C:\Program Files (x86)\LibreOffice\program\soffice.exe"),
        Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "LibreOffice" / "program" / "soffice.exe",
    ]
    for candidate in windows_candidates:
        if candidate.exists():
            return candidate

    # Common Linux / macOS locations
    unix_candidates = [
        Path("/usr/bin/soffice"),
        Path("/usr/local/bin/soffice"),
        Path("/Applications/LibreOffice.app/Contents/MacOS/soffice"),
    ]
    for candidate in unix_candidates:
        if candidate.exists():
            return candidate

    return None


def find_pandoc() -> Optional[Path]:
    """Locate pandoc executable if available."""
    pandoc_path = shutil.which("pandoc")
    return Path(pandoc_path) if pandoc_path else None


def compute_numpy_table_summary(columns: Dict[str, List[float]]) -> Dict[str, Dict[str, float]]:
    """
    Compute descriptive statistics for numerical columns in data tables using NumPy.
    Falls back to Python standard statistics if NumPy is not installed.
    """
    results: Dict[str, Dict[str, float]] = {}
    try:
        import numpy as np  # type: ignore
        for col_name, values in columns.items():
            if not values:
                continue
            arr = np.array(values, dtype=float)
            results[col_name] = {
                "mean": float(np.mean(arr)),
                "std": float(np.std(arr)),
                "min": float(np.min(arr)),
                "max": float(np.max(arr)),
                "median": float(np.median(arr))
            }
    except ImportError:
        import statistics
        for col_name, values in columns.items():
            if not values:
                continue
            results[col_name] = {
                "mean": statistics.mean(values),
                "std": statistics.stdev(values) if len(values) > 1 else 0.0,
                "min": min(values),
                "max": max(values),
                "median": statistics.median(values)
            }
    return results


def convert_markdown_to_document(
    input_md_path: Path,
    output_format: str = "odt",
    output_path: Optional[Path] = None,
) -> Path:
    """
    Convert a Markdown thesis draft to ODT, DOCX, PDF, or LaTeX.

    Args:
        input_md_path: Path to source markdown file.
        output_format: Target format ('odt', 'docx', 'pdf', 'latex', 'html').
        output_path: Optional custom destination path.

    Returns:
        Path to the generated document file.
    """
    input_md_path = Path(input_md_path).resolve()
    if not input_md_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_md_path}")

    fmt = output_format.lower().lstrip(".")
    target_ext = f".{fmt}"
    out_file = output_path or input_md_path.with_suffix(target_ext)

    pandoc = find_pandoc()
    soffice = find_libreoffice()

    # Method 1: Pandoc direct conversion
    if pandoc:
        cmd = [
            str(pandoc),
            str(input_md_path),
            "-o", str(out_file),
            "--from", "markdown+smart+tex_math_dollars",
        ]
        if fmt == "pdf":
            cmd.extend(["--pdf-engine", "xelatex"])
        
        try:
            subprocess.run(cmd, check=True, capture_output=True, text=True)
            if out_file.exists():
                return out_file
        except subprocess.CalledProcessError:
            pass  # Fall back to LibreOffice pipeline

    # Method 2: Headless LibreOffice conversion
    if soffice:
        out_dir = out_file.parent
        # If converting to PDF from intermediate odt or html
        cmd = [
            str(soffice),
            "--headless",
            "--convert-to", fmt,
            "--outdir", str(out_dir),
            str(input_md_path)
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        # Expected output filename generated by LibreOffice
        expected = out_dir / (input_md_path.stem + f".{fmt}")
        if expected.exists():
            if expected != out_file:
                shutil.move(str(expected), str(out_file))
            return out_file
        raise RuntimeError(f"LibreOffice conversion failed: {proc.stderr or proc.stdout}")

    # Fallback: If neither is installed, write a formatted HTML/LaTeX text bundle
    if fmt in ("html", "htm"):
        import html
        raw_text = input_md_path.read_text(encoding="utf-8")
        html_content = f"<!DOCTYPE html><html><head><meta charset='utf-8'><title>{input_md_path.stem}</title></head><body><pre>{html.escape(raw_text)}</pre></body></html>"
        out_file.write_text(html_content, encoding="utf-8")
        return out_file

    raise RuntimeError(
        f"Neither LibreOffice (soffice) nor Pandoc were found to convert to .{fmt}.\n"
        f"Please install LibreOffice from https://www.libreoffice.org or Pandoc from https://pandoc.org"
    )


def main() -> int:
    """CLI test runner for export bridge."""
    import argparse
    parser = argparse.ArgumentParser(description="OpenDraft LibreOffice & Document Export Bridge")
    parser.add_argument("input", type=str, help="Input Markdown file")
    parser.add_argument("--format", "-f", default="odt", choices=["odt", "docx", "pdf", "html", "latex"], help="Target format")
    parser.add_argument("--output", "-o", type=str, help="Output file path")
    args = parser.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output) if args.output else None

    try:
        result = convert_markdown_to_document(in_path, output_format=args.format, output_path=out_path)
        print(f"[OK] Successfully exported document to: {result}")
        return 0
    except Exception as e:
        print(f"[ERROR] Export failed: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
